server:
  port: 8082

spring:
  profiles:
    active: dev
  application:
    name: skydive-forecast-analysis-service
  jpa:
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    database-change-log-table: skydive-forecast-analysis.DATABASECHANGELOG
    database-change-log-lock-table: skydive-forecast-analysis.DATABASECHANGELOGLOCK

springdoc:
  api-docs:
    path: /v3/api-docs/analyses
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs/analyses.yaml

jwt:
  secret: change-me-please-and-make-it-at-least-32-characters-long

resilience4j.circuitbreaker:
  instances:
    myService:
      slidingWindowSize: 10
      failureRateThreshold: 50
      waitDurationInOpenState: 100
